filebeat.inputs:
- type: filestream
  id: spring-boot-logs
  enabled: true
  paths:
    - /var/log/spring-boot/*.log
  parsers:
    - multiline:
        type: pattern
        pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
        negate: true
        match: after

- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  # username: "elastic"
  # password: "changeme"

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
